### PR TITLE
convert newlines in replacements to be line breaks in the generated docx

### PR DESCRIPTION
**Pull request by mmmries**
This addresses #2

@paulcsmith this is definitely not ready for merging, but I wanted to just take a quick pass at the problem to see what would be involved with making it possible.

The gist of it is that instead of just replacing the contents of individual text nodes you actually have to create a new list of nodes (multiple text nodes separated by linebreak nodes) and then inject that new set of nodes into the document before removing the original node.

The difficult thing right now is that passing in the option to convert newlines happens in DocxTemplater, but the actual replacing of xml values happens way down in the NodesToFix class. So we will need to think about how to structure the the interaction between the code that is walking the xml trees and the code that knows what types of replacements it is supposed to perform.

### CODE REVIEW

**Comment by paulcsmith** [comment]
Ok I'll take a look soon! I skimmed over it and I can see what you mean here. I'll sit on it for a bit and we can definitely discuss it more. Seems like an interesting problem :)

**Comment by mmmries** [comment]
@giantchiprel if you need to use this feature really soon I would suggest changing your gemfile like this:

``` ruby
gem "docx_templater", :git => "git@github.com:BaseCampOps/docx_templater.git", :branch => "newline_conversion"
```

That way you can pull down the experimental version and give feedback until we have time to review and decide on how we will merge this into a stable release.

**Comment by leducmarc** [comment]
Awesome sounds good! I'll give it a try, thanks!

**Comment by mmmries** [comment]
So I worked on this a bit tonight and I was taking the tact of trying to make different replacers. The idea was that the DocxTemplater which build a replacer when it first get initialized and then it would use that replacer wherever it found and tagged a replacement.

But this approach is not going to work out. Part of the problem is that if you ever have a node with two replacements the first one will execute and change the XML structure, then the second one will fail because it will try to change the XML structure on a node that has already been removed from the XML tree...

So I am thinking I'll take another run at this and instead implement the newline conversion as a post-processing filter. So all the replacements would happen normally and then the DocxTemplater class would optionally pass the resulting XML through post processing filters (a line converter would be the first one supported). That way we aren't changing the XML structure during the replacement process.

@paulcsmith if you have any other ideas about how to handle this I am totally open for suggestions.

**Comment by leducmarc** [comment]
Just tried the \n out and it works!

Thanks again!

**Comment by mmmries** [comment]
This has been superceded by #4

**Pull request closed without merging**
